MODULE MOD_AGGREGATE_PAR

 USE IMODVAR, ONLY : DP_KIND
 INTEGER,PARAMETER :: BLOCKSIZE=500000
 CHARACTER(LEN=256) :: FNAME,OUTPUTDIR
 CHARACTER(LEN=256),ALLOCATABLE,DIMENSION(:) :: FLIST
 INTEGER :: IPRJ,ICONSISTENT,IAGGREGATE,IWHB,IWINDOW
 REAL(KIND=DP_KIND), PARAMETER :: EPS=1.0D0
 REAL(KIND=DP_KIND), PARAMETER :: KERROR=1.0D0,CERROR=1.0D0
 REAL(KIND=DP_KIND) :: CMIN,XMIN,YMIN,XMAX,YMAX,CELLSIZE
 
 CHARACTER(LEN=256) :: SORTFILE 
 CHARACTER(LEN=256) :: INDIR
 CHARACTER(LEN=256) :: CONDIR
 CHARACTER(LEN=256) :: MODELDIR

 END MODULE MOD_AGGREGATE_PAR