MODULE MOD_DEVWEL_PAR

USE IMODVAR, ONLY : DP_KIND

TYPE HEADEROBJ
 CHARACTER(LEN=52) :: CID,LIC,CTYPE
 REAL(KIND=DP_KIND) :: ELEV,TDEPTH,X,Y
END TYPE HEADEROBJ
TYPE(HEADEROBJ),ALLOCATABLE,DIMENSION(:) :: HEADER

TYPE DIROBJ
 CHARACTER(LEN=52) :: CID
 REAL(KIND=DP_KIND) :: MD,INC,AZIM
END TYPE DIROBJ
TYPE(DIROBJ),ALLOCATABLE,DIMENSION(:) :: DRC

TYPE CINT1OBJ
 CHARACTER(LEN=52) :: CID,CDATE,CTYPE
 REAL(KIND=DP_KIND) :: UD,LD
END TYPE CINT1OBJ
TYPE(CINT1OBJ),ALLOCATABLE,DIMENSION(:) :: CINT1

TYPE CINT2OBJ
 CHARACTER(LEN=52) :: CID,CDATE,CTYPE
 REAL(KIND=DP_KIND) :: UD,LD
END TYPE CINT2OBJ
TYPE(CINT2OBJ),ALLOCATABLE,DIMENSION(:) :: CINT2
REAL(KIND=DP_KIND),ALLOCATABLE,DIMENSION(:) :: ZDD,ZD1,ZD2,ZD3
REAL(KIND=DP_KIND),ALLOCATABLE,DIMENSION(:) :: IORDER,JORDER,KORDER

END MODULE MOD_DEVWEL_PAR