p:\1206764-imod\imod30\testbank\runs\test_ALL\results
2,2,1,0,1,0,0,0
1,0,0,0,0,0
150,20,0.0001,10.0,0.98
200000.00,400000.00,202500.00,402500.00,25.00,0.0
ACTIVE MODULES
0,0     (cap)
1,2,1,2 (bnd)
1,2,1,2 (shd)
1,2,1,2 (kdw)
1,2,1,2 (vcw)
0,0     (sto)
0,2,1,2 (top)
0,2,1,2 (bot)
0,2,1,2 (pwt)
0,2,1,2 (ani)
0,2,1,2 (hfb)
0,2,1,2 (wel)
0,2,1,2 (drn)
0,2,1,2 (riv)
0,2,1,2 (evt)
0,2,1,2 (ghb)
0,2,1,2 (rch)
1,2,1,2 (olf)
0,2,1,2 (chd)
0,2,1,2 (isg)
p:\1206764-imod\imod30\testbank\runs\test_ALL\boundary\imodflow_ibound1.idf
MODULES FOR EACH LAYER
0,(cap)
2,(bnd)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\boundary\imodflow_ibound1.idf
2,1.0,0.0,1.0
2,(shd)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\starting_heads\imodflow_shead1.idf
2,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\starting_heads\imodflow_shead2.idf
2,(kdw)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\transmissivity\imodflow_kd1.idf
2,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\transmissivity\imodflow_kd2.idf
1,(vcw)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\vertical_resistance\imodflow_c1.idf
0,(sto)
2,(top)
1,1.0,0.0,10.0
2,1.0,0.0,-10.0
2,(bot)
1,1.0,0.0,0.0
2,1.0,0.0,-50.0
1,(pwt)
1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\pwt\imodflow_pwt_ilay1.idf
1.0,0.0,0.15
1.0,0.0,5.0
1.0,0.0,0.0
1.0,0.0,-5.0
1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\pwt\imodflow_pwt_c1.idf
1,(ani)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\anisotropy\imodflow_anifct1.idf
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\anisotropy\imodflow_anihk1.idf
1,(hfb)
2,0.01,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\horizontal_barrier\imodflow_hfb2.gen
PACKAGES FOR EACH LAYER AND STRESS-PERIOD
1,0.00,steady-state,1
2,(wel)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\wells\imodflow_well1.ipf
0,0.5,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\wells\imodflow_well2.ipf
1,(drn)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\drainage\imodflow_drn_cond1.idf
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\drainage\imodflow_drn_elev1.idf
1,(riv)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\rivers\imodflow_riv_cond1.idf
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\rivers\imodflow_riv_stage1.idf
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\rivers\imodflow_riv_rbot1.idf
1,1.0,0.0,1.0
1,(evt)
1,1.0,0.0,0.95
1,1.0,0.0,4.0
1,1.0,0.0,1.0
1,(ghb)
1,1.0,0.0,10.0
1,1.0,0.0,1.0
1,(rch)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\recharge\imodflow_recharge1.idf
1,(olf)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\overlandflow\imodflow_olf1.idf
1,(chd)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\constanthead\imodflow_chead1.idf
1,(isg)
1,p:\1206764-imod\imod30\testbank\runs\test_ALL\segment_rivers\river.isg
