p:\1206764-imod\imod30\testbank\runs\test_ALL\results
2,2,1,0,1,0,0,0
1,0,0,0,0,0
150,20,0.0001,10.0,0.98
200000.00,400000.00,202500.00,402500.00,25.00,0.0
ACTIVE MODULES
0,0     (cap)
1,2,1,2 (bnd)
1,2,1,2 (shd)
1,2,1,2 (kdw)
1,2,1,2 (vcw)
0,0     (sto)
0,2,1,2 (top)
0,2,1,2 (bot)
0,2,1,2 (pwt)
0,2,1,2 (ani)
0,2,1,2 (hfb)
0,2,1,2 (wel)
0,2,1,2 (drn)
1,2,1,2 (riv)
0,2,1,2 (evt)
0,2,1,2 (ghb)
0,2,1,2 (rch)
0,2,1,2 (olf)
0,2,1,2 (chd)
0,2,1,2 (isg)
p:\1206764-imod\imod30\testbank\runs\test_ALL\boundary\imodflow_ibound1.idf
MODULES FOR EACH LAYER
0,(cap)
2,(bnd)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\boundary\imodflow_ibound1.idf
2,1.0,0.0,1.0
2,(shd)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\starting_heads\imodflow_shead1.idf
2,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\starting_heads\imodflow_shead2.idf
2,(kdw)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\transmissivity\imodflow_kd1.idf
2,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\transmissivity\imodflow_kd2.idf
1,(vcw)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\vertical_resistance\imodflow_c1.idf
0,(sto)
0,(top)
0,(bot)
0,(pwt)
0,(ani)
0,(hfb)
PACKAGES FOR EACH LAYER AND STRESS-PERIOD
1,0.00,steady-state,1
0,(wel)
0,(drn)
1,(riv)
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\rivers\imodflow_riv_cond1.idf
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\rivers\imodflow_riv_stage1.idf
1,1.0,0.0,p:\1206764-imod\imod30\testbank\runs\test_ALL\rivers\imodflow_riv_rbot1.idf
1,1.0,0.0,1.0
0,(evt)
0,(ghb)
0,(rch)
0,(olf)
0,(chd)
0,(isg)

