MODULE MOD_EXTRACTIPF_UTL

USE WINTERACTER
USE RESOURCE
USE IMODVAR, ONLY : IDIAGERROR
USE MOD_POLYGON_DRAW
USE MOD_POLYGON_UTL
USE MOD_POLYGON_PAR
USE MOD_IPF_PAR
USE MOD_IPF, ONLY : IPFDEALLOCATE

CONTAINS

 !###======================================================================
 SUBROUTINE EXTRACTIPF1CLOSE()
 !###======================================================================
 IMPLICIT NONE

 IDIAGERROR=1

 IPF(1)%IP=0
 !NSEL=0 !SUM(IPF(1)%IP)
 CALL IPFDEALLOCATE()

 CALL POLYGON1DRAWSHAPE(1,SHP%NPOL)
 CALL POLYGON1CLOSE()

 CALL WINDOWSELECT(0)
 CALL WMENUSETSTATE(ID_EXTRACTIPF,2,0)

 CALL WDIALOGSELECT(ID_DEXTRACT)
 CALL WDIALOGUNLOAD()
 CALL WDIALOGSELECT(ID_DIPFINFOFIND)
 CALL WDIALOGUNLOAD()

 IDIAGERROR=0

! CALL IDFPLOT(1)

 END SUBROUTINE EXTRACTIPF1CLOSE

END MODULE MOD_EXTRACTIPF_UTL
