MODULE MOD_IDFEDIT_UTL

USE MOD_IDFEDIT_PAR
USE MOD_POLYGON_PAR
USE MOD_POLYGON_UTL
USE MOD_POLYGON_DRAW

CONTAINS

 !###======================================================================
 SUBROUTINE IDFEDITCLOSE()
 !###======================================================================
 IMPLICIT NONE

 IDIAGERROR=1

 CALL POLYGON1DRAWSHAPE(1,SHP%NPOL); CALL POLYGON1CLOSE()

 LPLOTYSEL=.FALSE.
 IF(ALLOCATED(ITHRD))DEALLOCATE(ITHRD)
 CALL POLYGON1DEALLOCATE_SELIDF()
 IF(ALLOCATED(XGRIDSIZE))DEALLOCATE(XGRIDSIZE)
 
 CALL WINDOWSELECT(0); CALL WMENUSETSTATE(ID_IDFEDIT,2,0)

 CALL WDIALOGSELECT(ID_DIDFEDIT); CALL WDIALOGUNLOAD()
 CALL WDIALOGSELECT(ID_DIDFEDITCALC); CALL WDIALOGUNLOAD()
 CALL WDIALOGSELECT(ID_DIDFEDITLOGICAL); CALL WDIALOGUNLOAD()

 IDIAGERROR=0

 END SUBROUTINE IDFEDITCLOSE
 
END MODULE MOD_IDFEDIT_UTL