MODULE MOD_TB_PAR

CHARACTER(LEN=256) :: CONFNAME,OUTMAP,REPLACESTRING,OUTDIR
INTEGER :: IUOUT,IUOUTG
INTEGER :: NEXE
REAL :: THRESHOLD
TYPE TEXE
 CHARACTER(LEN=256) :: FNAME
 CHARACTER(LEN=52) :: ALIAS
 INTEGER :: IACT
 INTEGER :: IMAP
END TYPE TEXE
TYPE(TEXE),ALLOCATABLE,DIMENSION(:) :: EXE
INTEGER :: NRUN
TYPE TRUN
 CHARACTER(LEN=256) :: FNAME
END TYPE TRUN
TYPE(TRUN),POINTER,DIMENSION(:) :: RUN,RUN_BU

END MODULE MOD_TB_PAR