!!  Copyright (C) Stichting Deltares, 2005-2017.
!!
!!  This file is part of iMOD.
!!
!!  This program is free software: you can redistribute it and/or modify
!!  it under the terms of the GNU General Public License as published by
!!  the Free Software Foundation, either version 3 of the License, or
!!  (at your option) any later version.
!!
!!  This program is distributed in the hope that it will be useful,
!!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!  GNU General Public License for more details.
!!
!!  You should have received a copy of the GNU General Public License
!!  along with this program.  If not, see <http://www.gnu.org/licenses/>.
!!
!!  Contact: imod.support@deltares.nl
!!  Stichting Deltares
!!  P.O. Box 177
!!  2600 MH Delft, The Netherlands.
MODULE MOD_SCEN_PAR

INTEGER,PARAMETER :: MAXSDF   =10 !# maximum of sdf-files in scn-file
INTEGER,PARAMETER :: MXSCEN   =8 !sik number 9=simgro
INTEGER,PARAMETER :: MXPACKAGE=7 !## maximum number of packages
!#obj. voor packages to be manipulated
TYPE SCENOBJ
 CHARACTER(LEN=24) :: SCENDEF
 INTEGER :: N
 INTEGER :: IS1,IS2
 INTEGER :: IL1,IL2
 INTEGER :: IY1,IY2
 INTEGER :: IM1,IM2
 INTEGER :: ID1,ID2
 CHARACTER(LEN=24),DIMENSION(MXPACKAGE) :: PACKAGE
 CHARACTER(LEN=256),DIMENSION(MXPACKAGE) :: IDFNAME
 REAL,DIMENSION(MXPACKAGE) :: IMP
 REAL,DIMENSION(MXPACKAGE) :: FCT
END TYPE SCENOBJ
TYPE(SCENOBJ),DIMENSION(MXSCEN) :: SCEN
CHARACTER(LEN=256),ALLOCATABLE,DIMENSION(:,:) :: SDFNAME
INTEGER,ALLOCATABLE,DIMENSION(:) :: NSDFNAME

CHARACTER(LEN=256) :: SCNDIR,SCNFNAME

CONTAINS

 !###======================================================================
 SUBROUTINE SCEN1INITVAR()
 !###======================================================================
 INTEGER :: I

 SCEN%IY1=1994
 SCEN%IY2=2007
 SCEN%IM1=1
 SCEN%IM2=12
 SCEN%ID1=1
 SCEN%ID2=31
 SCEN%IL1=1
 SCEN%IL2=1
 SCEN%IS1=1
 SCEN%IS2=1
 DO I=1,MXSCEN
  SCEN(I)%IMP=0.0
  SCEN(I)%FCT=1.0
  SCEN(I)%IDFNAME=''
  SCEN(I)%PACKAGE=''
 END DO

 SCEN(1)%SCENDEF='WELLS'
 SCEN(1)%N=4
 SCEN(1)%PACKAGE(1)='WEL-SYSTEM'
 SCEN(1)%PACKAGE(2)='WEL-LAYER'
 SCEN(1)%PACKAGE(3)='WEL-DATE'
 SCEN(1)%PACKAGE(4)='WEL-STRENGTH'

 SCEN(2)%SCENDEF='DRAINS'
 SCEN(2)%N=5
 SCEN(2)%PACKAGE(1)='DRN-SYSTEM'
 SCEN(2)%PACKAGE(2)='DRN-LAYER'
 SCEN(2)%PACKAGE(3)='DRN-DATE'
 SCEN(2)%PACKAGE(4)='DRN-CONDUCTANCE'
 SCEN(2)%PACKAGE(5)='DRN-ELEVATION'

 SCEN(3)%SCENDEF='RIVERS'
 SCEN(3)%N=7
 SCEN(3)%PACKAGE(1)='RIV-SYSTEM'
 SCEN(3)%PACKAGE(2)='RIV-LAYER'
 SCEN(3)%PACKAGE(3)='RIV-DATE'
 SCEN(3)%PACKAGE(4)='RIV-CONDUCTANCE'
 SCEN(3)%PACKAGE(5)='RIV-STAGE'
 SCEN(3)%PACKAGE(6)='RIV-BOTTOM'
 SCEN(3)%PACKAGE(7)='RIV-RATIOFACTOR'

 SCEN(4)%SCENDEF='EVAPOTRANSPIRATION'
 SCEN(4)%N=6
 SCEN(4)%PACKAGE(1)='EVT-SYSTEM'
 SCEN(4)%PACKAGE(2)='EVT-LAYER'
 SCEN(4)%PACKAGE(3)='EVT-DATE'
 SCEN(4)%PACKAGE(4)='EVT-STRENGTH'
 SCEN(4)%PACKAGE(5)='EVT-SURFACE'
 SCEN(4)%PACKAGE(6)='EVT-DEPTH'

 SCEN(5)%SCENDEF='GENERAL_HEAD_BOUNDARY'
 SCEN(5)%N=5
 SCEN(5)%PACKAGE(1)='GHB-SYSTEM'
 SCEN(5)%PACKAGE(2)='GHB-LAYER'
 SCEN(5)%PACKAGE(3)='GHB-DATE'
 SCEN(5)%PACKAGE(4)='GHB-CONDUCTANCE'
 SCEN(5)%PACKAGE(5)='GHB-ELEVATION'

 SCEN(6)%SCENDEF='RECHARGE'
 SCEN(6)%N=4
 SCEN(6)%PACKAGE(1)='RECHARGE-SYSTEM'
 SCEN(6)%PACKAGE(2)='RECHARGE-LAYER'
 SCEN(6)%PACKAGE(3)='RECHARGE-DATE'
 SCEN(6)%PACKAGE(4)='RECHARGE-STRENGTH'

 SCEN(7)%SCENDEF='OVERLANDFLOW'
 SCEN(7)%N=4
 SCEN(7)%PACKAGE(1)='OLF-SYSTEM'
 SCEN(7)%PACKAGE(2)='OLF-LAYER'
 SCEN(7)%PACKAGE(3)='OLF-DATE'
 SCEN(7)%PACKAGE(4)='OLF-ELEVATION'

 SCEN(8)%SCENDEF='CONSTANT_HEAD'
 SCEN(8)%N=4
 SCEN(8)%PACKAGE(1)='CHD-SYSTEM'
 SCEN(8)%PACKAGE(2)='CHD-LAYER'
 SCEN(8)%PACKAGE(3)='CHD-DATE'
 SCEN(8)%PACKAGE(4)='CHD-HEAD'

! SCEN(9)%SCENDEF='SIMGRO'
! SCEN(9)%N=6
! SCEN(9)%PACKAGE(1)='LANDGEBRUIK'
! SCEN(9)%PACKAGE(2)='BEWORTELING'
! SCEN(9)%PACKAGE(3)='BODEMTYPE'
! SCEN(9)%PACKAGE(4)='BEREGENINGSLAAG'
! SCEN(9)%PACKAGE(5)='BEREGEN(0=OFF|1=GW|2=SW)'
! SCEN(9)%PACKAGE(6)='SOPP(VERHARD-OPPERVLAK)'

 END SUBROUTINE SCEN1INITVAR

END MODULE MOD_SCEN_PAR

