MODULE MOD_SUBSURFEX_PAR
 
 INTEGER :: CLICKS,POLYGONNR
 INTEGER :: CLEAR
 INTEGER :: NROFCELLS
 INTEGER :: NPARAM
 INTEGER,ALLOCATABLE,DIMENSION(:) :: CELLS 
 INTEGER,ALLOCATABLE,DIMENSION(:) :: DATASELECTION
 
 REAL :: GRIDSIZE,INIXMIN,INIYMIN,INIXMAX,INIYMAX
 REAL :: XMIN,YMIN,XMAX,YMAX,OLDX,OLDY,NEWX,NEWY,FIRSTX,FIRSTY
 REAL,ALLOCATABLE,DIMENSION(:) :: VERTICESX,VERTICESY 
 
 CHARACTER(LEN=50) :: PROJECT 
 CHARACTER(LEN=52),ALLOCATABLE,DIMENSION(:) :: PARAM,HEADER
 CHARACTER(LEN=256),POINTER,DIMENSION(:) :: FOLDERNAMES
 CHARACTER(LEN=256),POINTER,DIMENSION(:) :: PROJECTNAMES 

 LOGICAL :: MOVE,DRAW
 
END MODULE MOD_SUBSURFEX_PAR
