!!  Copyright (C) Stichting Deltares, 2005-2018.
!!
!!  This file is part of iMOD.
!!
!!  This program is free software: you can redistribute it and/or modify
!!  it under the terms of the GNU General Public License as published by
!!  the Free Software Foundation, either version 3 of the License, or
!!  (at your option) any later version.
!!
!!  This program is distributed in the hope that it will be useful,
!!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!  GNU General Public License for more details.
!!
!!  You should have received a copy of the GNU General Public License
!!  along with this program.  If not, see <http://www.gnu.org/licenses/>.
!!
!!  Contact: imod.support@deltares.nl
!!  Stichting Deltares
!!  P.O. Box 177
!!  2600 MH Delft, The Netherlands.
!!
MODULE MOD_IPEST_ANALYSER

USE IMODVAR, ONLY : DP_KIND,SP_KIND
USE MODPLOT, ONLY : MPW
USE WINTERACTER
USE RESOURCE
USE MOD_DBL
USE MOD_GRAPH, ONLY : GRAPH_PLOTAXES,AXESOBJ,GRAPHUNITS,GRAPHAREA

TYPE(AXESOBJ),PRIVATE :: AXES

CONTAINS

 !###======================================================================
 SUBROUTINE IPEST_ANALYSE_MAIN(ITYPE,MESSAGE) 
 !###======================================================================
 IMPLICIT NONE
 INTEGER,INTENT(IN) :: ITYPE
 TYPE(WIN_MESSAGE),INTENT(IN) :: MESSAGE
 
 CALL WDIALOGSELECT(MESSAGE%WIN) 
  
 SELECT CASE (ITYPE)
 
  CASE (PUSHBUTTON)
   SELECT CASE (MESSAGE%VALUE1)
    CASE (IDCANCEL)
     CALL IPEST_ANALYSE_CLOSE()
    CASE (IDHELP)
     CALL IPEST_ANALYSE_PLOTGRAPH()
   END SELECT
   
  CASE (FIELDCHANGED)
   SELECT CASE (MESSAGE%VALUE1)
   END SELECT
   SELECT CASE (MESSAGE%VALUE2)
   END SELECT
  CASE (RESIZE,EXPOSE)
   CALL IPEST_ANALYSE_PLOTGRAPH()
  
 END SELECT
     
 END SUBROUTINE IPEST_ANALYSE_MAIN 
 
 !###======================================================================
 SUBROUTINE IPEST_ANALYSE_INIT() 
 !###======================================================================
 IMPLICIT NONE 
 
 CALL WINDOWSELECT(0); IF(WMENUGETSTATE(ID_IPESTANALYSER,2).EQ.1)THEN
  CALL IPEST_ANALYSE_CLOSE(); RETURN
 ENDIF

 CALL IPEST_ANALYSE_ALLOCATE()
 
 CALL WINDOWSELECT(0); CALL WMENUSETSTATE(ID_IPESTANALYSER,2,1)
 !## fill in dialog
 CALL WDIALOGLOAD(ID_DIPESTANALYSE,ID_DIPESTANALYSE)

! CALL WDIALOGPUTIMAGE(ID_OPEN1,ID_ICONOPEN,1)
 CALL WDIALOGSHOW(-1,-1,0,2)

 END SUBROUTINE IPEST_ANALYSE_INIT

 !###====================================================================
 SUBROUTINE IPEST_ANALYSE_PLOTGRAPH()
 !###====================================================================
 IMPLICIT NONE
 REAL(KIND=DP_KIND) :: YMIN,YMAX,XMIN,XMAX
 INTEGER :: I
 INTEGER,DIMENSION(6) :: GID
 DATA GID/IDF_PICTURE1,IDF_PICTURE2,IDF_PICTURE3,IDF_PICTURE4,IDF_PICTURE5,IDF_PICTURE6/

 CALL WDIALOGSELECT(ID_DIPESTANALYSE)
! CALL WDIALOGGETMENU(IDF_MENU1,J)

! IF(I.EQ.3)THEN
!  CALL DBL_IGRAREA(0.0D0,0.0D0,1.0D0,1.0D0)
!  CALL DBL_IGRUNITS(0.0D0,0.0D0,1.0D0,1.0D0)
!  CALL IGRAREACLEAR()
!  RETURN
! ENDIF

! CALL WDIALOGGETMENU(IDF_MENU1,I,YTITLE)
! CALL ISGATTRIBUTESPLOTISDEXTENT(XMIN,XMAX,YMIN,YMAX,I,J)

! CALL IGRCOLOURN(WRGB(255,255,255))

 DO I=1,SIZE(GID)
  CALL IGRSELECT(3,GID(I))
 
  CALL DBL_IGRAREA(0.0D0,0.0D0,1.0D0,1.0D0); CALL IGRAREACLEAR()
  CALL IGRFILLPATTERN(SOLID)
  XMIN=0.0D0
  YMIN=0.0D0
  XMAX=1.0D0
  YMAX=1.0D0
  CALL IPEST_ANALYSE_PLOT_AXES(XMIN,YMIN,XMAX,YMAX,.FALSE.,'XTITLE','YTITLE')

! CALL IGRCOLOURN(WRGB(255,0,0))
 
! IF(ISFR.EQ.0)THEN
!  DO K=1,TISD(J)-1
!   X1=UTL_IDATETOJDATE(DATISD2(J,K)%IDATE)
!   X2=UTL_IDATETOJDATE(DATISD2(J,K+1)%IDATE)
!   SELECT CASE (I)
!    CASE (1)
!     Y1=DATISD2(J,K)%WLVL
!     Y2=DATISD2(J,K+1)%WLVL
!
!   CALL DBL_IGRJOIN(REAL(X1,8),Y1,REAL(X2,8),Y1)
!   CALL DBL_IGRJOIN(REAL(X2,8),Y1,REAL(X2,8),Y2)
!  END DO
! ENDIF
 ENDDO
 
 CALL IGRSELECT(DRAWWIN,MPW%IWIN); CALL DBL_IGRAREA(0.0D0,0.0D0,1.0D0,1.0D0)
 CALL DBL_IGRUNITS(MPW%XMIN,MPW%YMIN,MPW%XMAX,MPW%YMAX,IOFFSET=1)

 ! CALL WDIALOGSELECT(ID_DISGATTRIBUTES)

 END SUBROUTINE IPEST_ANALYSE_PLOTGRAPH

!###====================================================================
 SUBROUTINE IPEST_ANALYSE_PLOT_AXES(XMIN,YMIN,XMAX,YMAX,LDATE,XTITLE,YTITLE)
 !###====================================================================
 IMPLICIT NONE
 CHARACTER(LEN=*),INTENT(IN) :: XTITLE,YTITLE
 REAL(KIND=DP_KIND),INTENT(IN) :: XMIN,YMIN,XMAX,YMAX
 LOGICAL,INTENT(IN) :: LDATE
 
 AXES%XMIN  =XMIN
 AXES%XMAX  =XMAX
 IF(AXES%XMAX.LE.AXES%XMIN)THEN
  AXES%XMIN=AXES%XMIN-1.0D0
  AXES%XMAX=AXES%XMAX+1.0D0
 ENDIF
 AXES%YMIN  =YMIN
 AXES%YMAX  =YMAX
 IF(AXES%YMAX.LE.AXES%YMIN)THEN
  AXES%YMIN=AXES%YMIN-1.0D0
  AXES%YMAX=AXES%YMAX+1.0D0
 ENDIF
 AXES%IFIXX =0 
 AXES%IFIXY =0 
 AXES%IFIXY2=0 
 AXES%XINT  =1.0D0 
 AXES%YINT  =1.0D0 
 AXES%XOFFSET=0 
 AXES%LDATE  =LDATE
 AXES%XTITLE=TRIM(XTITLE)
 AXES%YTITLE=TRIM(YTITLE)
 AXES%IAXES=(/1,0/)       !## left/bottom axes only
 AXES%XFACTOR=1.0D0
 AXES%YFACTOR=1.0D0
 AXES%DXAXESL=40.0D0  !## 1/40.0D0 als rand
 AXES%DYAXESB=20.0D0
 AXES%DYAXEST=75.0D0
 AXES%DXAXESR=150.0D0
 AXES%TFONT=FFHELVETICA   !## text-font
 AXES%ICLRRASTER=WRGB(220,220,220)
 
 AXES%ICLRBACKGROUND=WRGB(123,152,168)

 !## plot axes and set units
 CALL GRAPH_PLOTAXES(AXES,1)

 END SUBROUTINE IPEST_ANALYSE_PLOT_AXES 
 
 !###======================================================================
 SUBROUTINE IPEST_ANALYSE_ALLOCATE()
 !###======================================================================
 IMPLICIT NONE

 ALLOCATE(GRAPHUNITS(6,1),GRAPHAREA(4,1))
 GRAPHUNITS(1,1)=0.0D0
 GRAPHUNITS(2,1)=0.0D0
 GRAPHUNITS(3,1)=1.0D0
 GRAPHUNITS(4,1)=1.0D0
 GRAPHUNITS(5,1)=0.0D0
 GRAPHUNITS(6,1)=1.0D0
 GRAPHAREA(1,1) =0.0D0
 GRAPHAREA(2,1) =0.0D0
 GRAPHAREA(3,1) =1.0D0
 GRAPHAREA(4,1) =1.0D0
 
 END SUBROUTINE IPEST_ANALYSE_ALLOCATE

 !###======================================================================
 SUBROUTINE IPEST_ANALYSE_DEALLOCATE()
 !###======================================================================
 IMPLICIT NONE
 
 IF(ALLOCATED(GRAPHUNITS))DEALLOCATE(GRAPHUNITS)
 IF(ALLOCATED(GRAPHAREA))DEALLOCATE(GRAPHAREA)

 END SUBROUTINE IPEST_ANALYSE_DEALLOCATE

 !###======================================================================
 SUBROUTINE IPEST_ANALYSE_CLOSE()
 !###======================================================================
 IMPLICIT NONE
 
 CALL WINDOWSELECT(0); CALL WMENUSETSTATE(ID_IPESTANALYSER,2,0)
 CALL IPEST_ANALYSE_DEALLOCATE() 
 CALL WDIALOGSELECT(ID_DIPESTANALYSE); CALL WDIALOGUNLOAD()

 END SUBROUTINE IPEST_ANALYSE_CLOSE
 
END MODULE MOD_IPEST_ANALYSER
