MODULE MOD_MOVIE_PAR

INTEGER,ALLOCATABLE,DIMENSION(:) :: IMANAGER
INTEGER,ALLOCATABLE,DIMENSION(:) :: IFILES
INTEGER,ALLOCATABLE,DIMENSION(:) :: LDATES
INTEGER,ALLOCATABLE,DIMENSION(:,:) :: FDATES
CHARACTER(LEN=256),ALLOCATABLE,DIMENSION(:) :: PLOTNAMES,OFNAMES

CHARACTER(LEN=4),DIMENSION(5) :: EXT
DATA EXT/'BMP ','PNG','JPG ','PCX ','AVI '/ !,'MPG'/

END MODULE MOD_MOVIE_PAR