MODULE MOD_MOVIE_PAR

INTEGER,ALLOCATABLE,DIMENSION(:) :: IDFSTYLE
INTEGER,ALLOCATABLE,DIMENSION(:) :: IFILES
INTEGER,ALLOCATABLE,DIMENSION(:) :: LDATES
INTEGER,ALLOCATABLE,DIMENSION(:,:) :: FDATES
CHARACTER(LEN=256),ALLOCATABLE,DIMENSION(:) :: PLOTNAMES

CHARACTER(LEN=4),DIMENSION(4) :: EXT
DATA EXT/'BMP ','JPG ','PCX ','AVI '/ !,'MPEG'/
!## png gave problem in Winteracter
!DATA EXT/'BMP ','PNG ','JPG ','PCX ','AVI ','MPEG'/

END MODULE MOD_MOVIE_PAR